# config.yaml
trainer:
  save_checkpoint_path: './model_checkpoints/'
  load_checkpoint_path: Null

torch:
  precision: 'medium'

data_loader:
  batch_size: 8
  num_workers: 0

model:
  max_epochs: 11
  hidden_dim: 768
  mlp_dim: 3072 
  num_layers: 1
  num_heads: 1
  output_size: 10
  learning_rate: 0.001
  weight_decay: 0.001
  kernel_sizes: [[2, 2, 2]]
  strides: [[2, 32, 32]]
  offsets: [[0, 0, 0]]
  
  use_pretrained: False
  use_pretrained_conv: False


ETRI_dataset:
  max_number_frames: 2
  remove_background: False
  single_camera: True
  elders_only: True

transforms:
  train:
    - type: min_max_normalization
      scale_up: True
    - type: ConvertToFloat32
    - type: PermuteDimensions
      order: [3, 0, 1, 2]
    - type: repeat_color_channel
    - type: sample_frames
      nth: 1
  test:
    - type: min_max_normalization
      scale_up: True
    - type: ConvertToFloat32
    - type: PermuteDimensions
      order: [3, 0, 1, 2]
    - type: repeat_color_channel
    - type: sample_frames
      nth: 1
